services:
  db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: ./.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    attach: false

volumes:
  postgres-data: